{% set version = "7.7.1" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 6181b3570c2f657d989b1141fb0c1a08eb5f08106ca577dc7dc52e7d0238379a
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch

  - fn: bazel
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: 4729bd4bb6443d77940d80ed5903c322f254f50d525aa06b7dc188ffd1dce978  # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-arm64   # [build_platform == "linux-aarch64"]
    sha256: f1c16e400fdc491ccc047e5689c5e85e45d2aceface1085d1605aaf3a5054383  # [build_platform == "linux-aarch64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 5d6c1053aebf68226815720ee7a35f07b6eef1dc3b13fa7eb71d884d40c0ae8d  # [build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain 0.3.2
    - openjdk
    - libprotobuf
    - sed
  host:
    - libabseil {{ libabseil }}
    - libprotobuf {{ libprotobuf }}

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  dev_url: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars
  description: A tool for generating singleton jars

extra:
  skip-lints:
    - missing_documentation
    - missing_hash
    - missing_source
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
