{% set version = "8.8.0" %}

{% set base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: singlejar
  version: {{ version }}

source:
  - url: {{ base_url }}/{{ version }}/bazel-{{ version }}-dist.zip
    sha256: 71cea4e6df77d5d85e185db7f238d96db50132bf40c94e4978a35d92eaf42108
    patches:
      # Keep these patches in sync with the relevant ones from bazel-feedstock.
      - patches/0001-allow-args-to-be-passed-to-bazel_build.patch
      - patches/0002-Build-with-native-dependencies.patch
      - patches/0003-use-C-17.patch
      - patches/0004-update-dependencies-version.patch
  - fn: bazel-{{ version }}
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-x86_64  # [build_platform == "linux-64"]
    sha256: 4b6a8be4bf1f1f3aac05a0b7ebccfe3c3f12ce6ddb4bdc6593904b9f872a5c3d  # [build_platform == "linux-64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-linux-arm64   # [build_platform == "linux-aarch64"]
    sha256: 0490da39cd9de866eb79790accd2df260e4cc86167c84457cc1a702d4058361f  # [build_platform == "linux-aarch64"]
    url: {{ base_url }}/{{ version }}/bazel_nojdk-{{ version }}-darwin-arm64  # [build_platform == "osx-arm64"]
    sha256: 795865814cfa6fed8d54350ada5d9a3e865b8441927092a004142fc7ef67d357  # [build_platform == "osx-arm64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - bazel-toolchain >=0.2.0,<0.5.0
    - openjdk
    - libprotobuf 7.35.1
    - sed
  host:
    - libabseil 20260526.0
    - libprotobuf 7.35.1
    - protobuf-bazel-rules >=33.5

test:
  commands:
    - test -f $PREFIX/bin/singlejar
    - test -f $PREFIX/bin/singlejar_local

about:
  home: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  dev_url: https://github.com/bazelbuild/bazel/tree/master/src/tools/singlejar
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: A tool for generating singleton jars
  description: A tool for generating singleton jars

extra:
  skip-lints:
    - missing_documentation
    - missing_hash
    - missing_source
  recipe-maintainers:
    - xhochy
    - h-vetinari
    - conda-forge/bazel
